### PR TITLE
Added a list question to select the request library to use in the dis…

### PR DESCRIPTION
**Pull request by MongeJp**
**Added a list question to select the request library to use in the discord bot template.**

Hey @harshil1712 basically what I did here was to add a new list question to choose from three request library options, Axios, got and node-fetch, and a four option to give the user the chance to do that on his own.

Those options are what I found as the most used but would you like to add/change/remove one of the library options?

Also i see that it went some formatting with the commit, if you want me to revert this please let me know 👋

### CODE REVIEW

**Comment by harshil1712** [comment]
Hey! Would really appreciate it if you can undo the format changes.

**Comment by MongeJp** [comment]
> Hey! Would really appreciate it if you can undo the format changes.

Sure thing, I just commit the undo of that format change.

**Comment by MongeJp** [comment]
Hey, @harshil1712  I made the changes a couple of weeks ago, could you please provide me with some feedback if it's possible, like if this doesn't satisfy the requirements of the issue? or should I make a change?

**Comment by harshil1712** [comment]
Hey @MongeJp, thank you! The PR is merged. I'll publish the changes once the rest of the issues are also completed. Thanks!

**Pull request merged**
